baseURL = 'https://uliananeu.github.io/'
languageCode = 'en-us'
title = 'Web Dev'
theme = 'paper' 

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  github = 'uliananeu'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'uliana-neustroeva'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/139770965?v=4'                 # gravatar email or image url
  name = 'Uliana Neustroeva'
  bio = 'A portfolio blog by Uliana Neustroeva'